### ISSUE TITLE
log-scale 

### ISSUE THREAD

**Issue by mardilos** [SneakySnail/LIPRAS#19]
Hi
I currently started using matlab and thus LIPRAS.

When i use the logscale for y-axes, Lipras uses the ln(Intensity).
Is it possible to switch that to the log10 in the code?

Best
Martin
![Lipras](https://user-images.githubusercontent.com/65020763/96006127-71349f00-0e3d-11eb-8374-7e2c202f3bdd.png)

**Comment by SneakySnail** [comment]
Martin,

 

I just changed it, download the latest version from MATLAB filexchange

 

Giovanni Esteves, Ph.D.

Materials Science and Engineering
