### ISSUE TITLE
Failure to Launch standalone v 466

### ISSUE THREAD

**Issue by sfields75** [SneakySnail/LIPRAS#20]
Hello,

After using standalone LIPRAS (version 466 from sourceforge: https://sourceforge.net/projects/lipras/) for some time without issue, I am receiving the attached error message during launch, and the GUI does not initialize.

![image](https://user-images.githubusercontent.com/81430489/112654870-3b510900-8e26-11eb-9222-8a752a65c42d.png)

Thank you.

**Comment by SneakySnail** [comment]
Solution to this is to delete the CTF folder. See the following link: https://www.mathworks.com/matlabcentral/answers/437462-why-am-i-not-able-to-execute-my-standalone-application-on-only-certain-end-user-machines

Thanks for bringing up this issue.
